### ISSUE TITLE
Improve automation of test

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_cti_processor#11]
Currently data import for tests are run manually 

https://github.com/muchdogesec/arango_cti_processor/blob/adding-tests/tests/README.md#test-10-validate-capec-attack-pattern---attck-attack-pattern-relationship-capec-attack

Is there a way we can take advantage of the stix2arango installed in arango_cti_processor to also include the data import in the test, so that is is 100% automatic?

If you can show me how on one test, I can retool the other tests.

**Comment by fqrious** [comment]
the step is as follows

1. prepare the bundle.json
2. import Stix2Arango from stix2arango
3. pass in all the needed keyword arguments (e.g `s2a = Stix2Arango(host_url="https://cti.blah.net:8529/", collection=...)`)
4. `s2a.run()`

**Comment by himynamesdave** [comment]
@fqrious can you show an example in this test 

https://github.com/muchdogesec/arango_cti_processor/blob/adding-tests/tests/test_1_1_capec_to_attack.py

using this s2a command

python3 stix2arango.py \
  --file tests/files/arango_cti_processor/arango-cti-capec-attack-update-1.json \
  --database arango_cti_processor_standard_tests \
  --collection mitre_capec \
  --stix2arango_note v3.10

**Comment by fqrious** [comment]
```python
from stix2arango.stix2arango import Stix2Arango

s2a = Stix2Arango(
        database="arango_cti_processor_standard_tests",
        collection="mitre_capec",
        stix2arango_note="v3.10",
        file="tests/files/arango_cti_processor/arango-cti-capec-attack-update-1.json"
    )

s2a.run()
```
