### ISSUE TITLE
sigma-cve relationships failing bug

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_cti_processor#17]
https://github.com/muchdogesec/arango_cti_processor/blob/adding-tests/tests/README.md#test-80-test-sigma-rule-indicator-to-cve-vulnerability

test is failing

```
        RETURN LENGTH(
          FOR doc IN sigma_rules_edge_collection
            FILTER doc._is_latest == true
            AND doc._arango_cti_processor_note == "sigma-cve"
            RETURN [doc]
        )
``` 

returns 0 results after test is run, suggesting no sros created.

**Comment by fqrious** [comment]
the files are outdated, sigma2stix no longer use `labels` but instead uses `external_references`. and that's why nothing was uploaded

**Comment by himynamesdave** [comment]
closing for #18
