### ISSUE TITLE
when creating cve-epss not objects (when don't exist) use same template as cve2stix

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_cti_processor#32]
If you need to create a new Note object, it should use the logic from cve2stix, creating notes as follows

https://github.com/muchdogesec/cve2stix?tab=readme-ov-file#note-sdo-note

**Comment by fqrious** [comment]
the object is created, the expected value is just wrong... see https://github.com/muchdogesec/arango_cti_processor/issues/31#issuecomment-2410904684
