### ISSUE TITLE
Test 9.0 is failing

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_cti_processor#38]
```shell
python3 -m unittest tests/test_09_0_modified_min.py
```

The CLI `modified_min` argument is 2022-01-01 so the expectation is that only one SRO is created by arango_cti_processor (1 time is younger than this (`2015-01-01T00:00:00.000Z`), one time is older than this (`2024-01-01T00:00:00.000Z`))

```shell
python3 -m unittest tests/test_09_0_modified_min.py
```

**Comment by fqrious** [comment]
https://github.com/muchdogesec/arango_cti_processor/blob/e93a3f1d1e783db54d880745f5544e44a803f5dd/tests/test_09_0_modified_min.py#L83C22-L83C49
> FOR doc IN `mitre_cwe_vertex_collection`

wrong collection, relationships are stored in `mitre_cwe_edge_collection`

every single query in that file is wrong
